### Lab experiment 1 - Machine Learning specialisation

Key/basic packages used for data analysis and machine
learning are
1. NumPy
2. Pandas
3. Matplotlib
4. SciPy

# NUMPY

Numpy is a python library for scientific computing

Installation:

**Mac and Linux**: pip install numpy
**Windows**: download the pre-built windows installer for NumPy manually

Numpy array is a collection of values with similar data type

RANK = Dimension

We can change the values of a numpy array (i.e numpy arrays are mutable)

#### Initialising arrays:

In [9]:
import numpy as np #import numpy package
a=np.array( [ 0, 1, 2 ]) #numpy with rank = 1 
print(type(a))
print(a.shape) #prints dimension of array
print(a[0], a[1], a[2])
a[0]=5
print(a) #Numpy arrays are mutable

<class 'numpy.ndarray'>
(3,)
0 1 2
[5 1 2]


In [10]:
b=np.array( [ [ 0, 1, 2 ] , [3, 4, 5 ] ] ) #numpy with rank = 2
print(b.shape,"\n")
print(b,"\n")
print( b[ 0, 0 ] , b[ 1, 2 ], b[ 1, 0 ])

(2, 3) 

[[0 1 2]
 [3 4 5]] 

0 5 3


#### Create a 3x3 array with all elements = 0

In [11]:
a=np.zeros( ( 3,3 ) ) #creates a 3x3 array with all elements = 0
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Create a 5x5 array with all elements = 1

In [12]:
b=np.ones( ( 5, 5 )) #creates a 3x3 array with all elements = 1
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Create a 3x3 array with all elements = some constant value 

In [13]:
c=np.full ( ( 3,3 ), 7) 
c

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

#### Create a random array

In [14]:
d=np.random.random( ( 3, 3 ))
d

array([[0.99183102, 0.25358412, 0.27728546],
       [0.78133956, 0.43150758, 0.162158  ],
       [0.00820041, 0.84884437, 0.97476496]])

#### Create a identity matrix

In [15]:
e=np.eye(7)
e

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

#### Conversion of list to an array:

In [16]:
li=[ 2, 3, 1, 5 ]
print(type(li))
f = np.array ( li )
print(f)
print(type(f))

<class 'list'>
[2 3 1 5]
<class 'numpy.ndarray'>


#### Arrays using arange function: ( regularly incrementing values )

In [17]:
g=np.arange(10)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
h = np.array( [ [ 0,1, 1.20] , [ 0, 4,5 ], [1+1j,5.,4.353 ] ] )
h

array([[0.   +0.j, 1.   +0.j, 1.2  +0.j],
       [0.   +0.j, 4.   +0.j, 5.   +0.j],
       [1.   +1.j, 5.   +0.j, 4.353+0.j]])

In [19]:
i = np.arange(1,11, dtype=np.float)
print(i)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]¶

In [20]:
#linspace - returns evenly spaced numbers over a specified interval.
j= np.linspace( 5, 18, 3) #generates 3 samples 
print(j)
j2 = np.linspace(2, 4, 5) #generates 5 samples 
print(j2)
j3=np.linspace (0,1) #default Num (number of samples to be generated)=50
print(j3)
np.linspace(2.0, 3.0, num=5)

[ 5.  11.5 18. ]
[2.  2.5 3.  3.5 4. ]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

## Numpy datatypes:

In [21]:
w=np.array ( [ 0 ,1 ] )
x=np.array ( [ 5.0 ,4.3 ] )
y=np.array ( [ 5, 6 ], dtype=np.int64)
z=np.array ( [ 5, 6 ], dtype=np.double)
print(w.dtype,x.dtype,y.dtype,z.dtype)

int64 float64 int64 float64


In [22]:
ar=np.array( [ [ -1,3 , 5,3.4], [ 4,6,4,3], [6, 5,7, .65] , [ 3,5,6,6.6]])
ar

array([[-1.  ,  3.  ,  5.  ,  3.4 ],
       [ 4.  ,  6.  ,  4.  ,  3.  ],
       [ 6.  ,  5.  ,  7.  ,  0.65],
       [ 3.  ,  5.  ,  6.  ,  6.6 ]])

#### SLICING:

In [30]:
temp= ar [ : 3, :: 2 ]
print(temp) #prints 3 rows with alternating columns 

[[-1.  5.]
 [ 4.  4.]
 [ 6.  7.]]


In [31]:
temp= ar [ : 5, :: 2 ]
print(temp) #prints 3 rows with alternating columns 

[[-1.  5.]
 [ 4.  4.]
 [ 6.  7.]
 [ 3.  6.]]


#### INTEGER ARRAY INDEXING: 

In [33]:
temp=ar[ [ 0 , 1, 2, 3 ], [ 3, 2, 1 , 0 ] ]
print(temp)
print("Prints the values of temp array at the indices (0,3), (1,2), (2,1), (3,0)")

[3.4 4.  5.  3. ]
Prints the values of temp array at the indices (0,3), (1,2), (2,1), (3,0)


#### BOOLEAN ARRAY INDEXING:

In [37]:
g_t_0=ar>0 #g_t_0 is an array with values of ar array such that elements > 0 
temp=ar[g_t_0]
print(ar)
print(temp)

[[-1.    3.    5.    3.4 ]
 [ 4.    6.    4.    3.  ]
 [ 6.    5.    7.    0.65]
 [ 3.    5.    6.    6.6 ]]
[3.   5.   3.4  4.   6.   4.   3.   6.   5.   7.   0.65 3.   5.   6.
 6.6 ]


## Operations on arrays:

In [46]:
a=np.array( [ 1, 2, 5, 3 ])
print(a+1) #adding 1 to all the elements of array
print(a-3) #Subtracting 3 to all the elements of array
print(a/2) 
print(a%2) 

[2 3 6 4]
[-2 -1  2  0]
[0.5 1.  2.5 1.5]
[1 0 1 1]
